name:
mode: "dev"
port: "8080"
version: "v0.0.1"


log:
  level: "info"
  filename: "Example.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  enable: true
  host: 127.0.0.1
  port: 13306
  user: "root"
  password: "123456"
  dbname: "test"
  max_open_conns: 200
  max_idle_coons: 50

redis:
  enable:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 6
  pool_size: 100

jwt:
  enable: true
  secret: "example"
  # 过期时间 单位：小时
  expire_duration: 2

snowflake:
  enable: true
  start_time: "2021-03-02"
  machine_id: 1
